### ISSUE TITLE
Restricted Software denied

### ISSUE THREAD

**Issue by AndrewIsaac** [Karaage-Cluster/karaage-software#1]
When I try to request restricted software I get:
Restricted Software denied.

This appears to be because there is the wrong test in:
karaage-software/kgsoftware/views.py
(line 43)

$ kg-manage shell
>>> from django.apps import apps
>>> apps.is_installed("kgsoftware.applications")
False

Should this be?
>>> apps.is_installed('karaage.plugins.kgsoftware')
True

**Comment by AndrewIsaac** [comment]
scrap that, looking at wrong version.
Still getting;
Restricted Software denied.

**Comment by vpac-gerrit** [comment]
What is your PLUGINS setting?
-- 
Brian May
Systems Administrator (Advanced Computing)
V3 Alliance | Accelerating Research

T: +613 9925 4267
A: RMIT Building 91, 110 Victoria Street, Carlton South, Victoria, Australia
W: www.v3.org.au

**Comment by AndrewIsaac** [comment]
> On 3 Mar 2015, at 2:35 pm, Gerrit <notifications@github.com> wrote:
> 
> What is your PLUGINS setting?

PLUGINS = [
    'kgapplications.plugin',
    'kgsoftware.plugin',
    'kgusage.plugin',
]

This is a migration from Karaage 2.6.4-1 to Karaage 3.1.13-1~bpo70+1
I've a sneaking suspicion that 'kgapplications.plugin' was disabled during the original migration.  But I've since re-migrated without complaint.

I get the following:
# kg-manage shell
>>> from django.apps import apps
>>> apps.is_installed("karaage.plugins.kgsoftware.applications")
False
>>> apps.is_installed("karaage.plugins.kgsoftware")
True

so I have a suspicion that I should start again from scratch.

**Comment by vpac-gerrit** [comment]
----- Original Message -----
> PLUGINS = [
> 'kgapplications.plugin',
> 'kgsoftware.plugin',
> 'kgusage.plugin',
> ]

Ok, I see your problem.

You will need to add karaage.plugins.kgsoftware.plugin.applications to the above list to get software applications to work.

Also note that all plugins are now prefixed with karaage.plugins.* although the old names will continue to work.
-- 
Brian May
Systems Administrator (Advanced Computing)
V3 Alliance | Accelerating Research

T: +613 9925 4267
A: RMIT Building 91, 110 Victoria Street, Carlton South, Victoria, Australia
W: www.v3.org.au

**Comment by brianmay** [comment]
----- Original Message -----
> Ok, I see your problem.
> 
> You will need to add karaage.plugins.kgsoftware.plugin.applications
> to the above list to get software applications to work.
> 
> Also note that all plugins are now prefixed with karaage.plugins.*
> although the old names will continue to work.
> --
> Brian May
> Systems Administrator (Advanced Computing)
> V3 Alliance | Accelerating Research

Hello,

Did this help?

For some reason my emails to github come out with the wrong sender, just testing if this works.
-- 
Brian May
Systems Administrator (Advanced Computing)
V3 Alliance | Accelerating Research

T: +613 9925 4267
A: RMIT Building 91, 110 Victoria Street, Carlton South, Victoria, Australia
W: www.v3.org.au

**Comment by AndrewIsaac** [comment]
> On 10 Mar 2015, at 12:26 pm, Brian May <notifications@github.com> wrote:
> 
> ----- Original Message -----
> > Ok, I see your problem.
> > 
> > You will need to add karaage.plugins.kgsoftware.plugin.applications
> > to the above list to get software applications to work.
> > 
> > Also note that all plugins are now prefixed with karaage.plugins.*
> > although the old names will continue to work.
> > --
> > Brian May
> > Systems Administrator (Advanced Computing)
> > V3 Alliance | Accelerating Research
> 
> Hello,
> 
> Did this help?

Haven't tested yet, but make sense.

Ta

**Comment by AndrewIsaac** [comment]
> On 10 Mar 2015, at 12:26 pm, Brian May <notifications@github.com> wrote:
> 
> ----- Original Message -----
> > Ok, I see your problem.
> > 
> > You will need to add karaage.plugins.kgsoftware.plugin.applications
> > to the above list to get software applications to work.

hmm

for:
PLUGINS = [
#    'kgapplications.plugin',
    'kgsoftware.plugin',
    'kgsoftware.plugin.applications',
    'kgusage.plugin',
]

I get (e.g. kg-manamge shell):
No module named plugin

comment out .applications runs (but still can't apply!)

**Comment by brianmay** [comment]
What version of Karaage is this?

You mean you commented out 'kgapplications.plugin' to fix the error? i.e. you left in 'kgsoftware.plugin.applications'?

kgsoftware.plugin.applications should automatically pull in kgapplications.plugin, so that error doesn't make sense.

Please can you try the following, and give me the output (some errors will occur, that is fine):

```
# kg-manage shell

import kgapplications.plugin
import karaage.plugins.kgapplications
karaage.plugins.kgapplications.plugin

from django.apps import apps
apps.is_installed("karaage.plugins.kgapplications")
apps.is_installed("karaage.plugins.kgsoftware.applications")
apps.get_app_configs()

**Comment by AndrewIsaac** [comment]
> On 16 Mar 2015, at 10:41 am, Brian May <notifications@github.com> wrote:
> 
> What version of Karaage is this?
ii  karaage3                              3.1.15-1~bpo70+1

> You mean you commented out 'kgapplications.plugin' to fix the error? i.e. you left in 'kgsoftware.plugin.applications'?

Tried many variants,
...

> Please can you try the following, and give me the output (some errors will occur, that is fine):
> 
> # kg-manage shell
> 
> import kgapplications.plugin
> import karaage.plugins.kgapplications
> karaage.plugins.kgapplications.plugin
> 
> from django.apps import apps
> apps.is_installed("karaage.plugins.kgapplications")
> apps.is_installed("karaage.plugins.kgsoftware.applications")
> apps.get_app_configs()

# kg-manage shell
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import kgapplications.plugin
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: No module named kgapplications.plugin
>>> import karaage.plugins.kgapplications
>>> karaage.plugins.kgapplications.plugin
<class 'karaage.plugins.kgapplications.plugin'>
>>> 
>>> from django.apps import apps
>>> apps.is_installed("karaage.plugins.kgapplications")
True
>>> apps.is_installed("karaage.plugins.kgsoftware.applications")
False
>>> apps.get_app_configs()
[<Karaage: karaage>, <plugin: kgapplications>, <plugin: kgsoftware>, <plugin: kgusage>, <AppConfig: djcelery>, <AppConfig: django_xmlrpc>, <AppConfig: captcha>, <AppConfig: ajax_select>, <AppConfig: jsonfield>, <AppConfig: django_tables2>, <AppConfig: methods>, <AppConfig: django>, <AppConfig: pipeline>, <ContentTypesConfig: contenttypes>, <SessionsConfig: sessions>, <SitesConfig: sites>, <HumanizeConfig: humanize>, <MessagesConfig: messages>, <StaticFilesConfig: staticfiles>]

**Comment by brianmay** [comment]
Ok, so karaage.plugins.kgsoftware.applications isn't getting loaded for some reason, that makes more sense.

What happens if you do:

```
# kg-manage shell
import karaage.plugins.kgsoftware.applications 
```

**Comment by AndrewIsaac** [comment]
> On 17 Mar 2015, at 10:45 am, Brian May <notifications@github.com> wrote:
> 
> Ok, so karaage.plugins.kgsoftware.applications isn't getting loaded for some reason, that makes more sense.
> 
> What happens if you do:
> 
> # kg-manage shell
> import karaage.plugins.kgsoftware.applications 

gets stranger, imports without complaint, but still shows up as not loaded

ta

# kg-manage shell
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import karaage.plugins.kgsoftware.applications
>>> from django.apps import apps
>>> apps.is_installed("karaage.plugins.kgapplications")
True
>>> apps.is_installed("karaage.plugins.kgsoftware.applications")
False
>>> apps.get_app_configs()
[<Karaage: karaage>, <plugin: kgapplications>, <plugin: kgsoftware>, <plugin: kgusage>, <AppConfig: djcelery>, <AppConfig: django_xmlrpc>, <AppConfig: captcha>, <AppConfig: ajax_select>, <AppConfig: jsonfield>, <AppConfig: django_tables2>, <AppConfig: methods>, <AppConfig: django>, <AppConfig: pipeline>, <ContentTypesConfig: contenttypes>, <SessionsConfig: sessions>, <SitesConfig: sites>, <HumanizeConfig: humanize>, <MessagesConfig: messages>, <StaticFilesConfig: staticfiles>]

**Comment by brianmay** [comment]
I see the problem. I think I gave you the wrong config value, sorry. From the sample config file, to enable everything:

```python
PLUGINS = [                                                                    
    'karaage.plugins.kgapplications.plugin',                                   
    'karaage.plugins.kgsoftware.plugin',                                       
    'karaage.plugins.kgsoftware.applications.plugin',                          
    'karaage.plugins.kgusage.plugin',                                          
]                                         
```

**Comment by AndrewIsaac** [comment]
nice work Brian,
that fixed it.

**Comment by brianmay** [comment]
Ok, good. Closing this issue.

For future reference, please submit all tickets against the Karaage package, thanks.
